### ISSUE TITLE
demo项目的github地址多少

### ISSUE THREAD

**Issue by OnlyChange** [xiaojiaqi/deploy-microservices-to-a-Kubernetes-cluster#1]

**Comment by xiaojiaqi** [comment]
所有的yaml 都在本项目里啊。

**Comment by OnlyChange** [comment]
serviceA-1.0.0.jar在哪放着呢

**Comment by OnlyChange** [comment]
> 所有的yaml 都在本项目里啊。
serviceA-1.0.0.jar在哪放着呢

**Comment by OnlyChange** [comment]
serviceA-1.0.0.jar在哪放着呢

**Comment by OnlyChange** [comment]
serviceA-1.0.0.jar、serviceB-1.0.0.jar、serviceC-1.0.0.jar在哪放着呢，你得开源serviceA、serviceB、serviceC项目

**Comment by xiaojiaqi** [comment]
镜像都有了，都在里面
